# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Đức Bệu
title: Người yêu cô nàng má bánh bao
email: ducnv1911@gmail.com
phone: 0913458796
website: Your website (eg. https://google.com)(optional)

# Dark Mode (true/false/never)
darkmode: false

# Social links
facebook_username: ThacSyAoE
instagram_username: potassium_duc
orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: 10 sự thật kinh hoàng về bản thân
about_profile_image: images/IMG_0106.jpg
about_content: | # this will include new lines to allow paragraphs
  Dưới đây là 10 sự thật kinh hoàng về bản thân anh
    - Điều thứ nhất: Tên khai sinh đầy đủ chính xác là: Nguyễn Khương Long. Ban đầu anh không có tên là Đức như hiện tại. Do sinh ra người anh hay ốm nên bố mẹ đổi tên lại thành Đức 
    như hiện tại để mong mọi điều tốt đẹp sẽ tới với bản thân anh.
    - Xuống với điều thứ 2: Anh sinh chính xác vào lúc 6h ngày 19 tháng 11 năm 1996. Hơn em tròn đúng 4 năm(hờ hờ tính cả năm nhuận nhé). Hồi bé anh không thích ngày này lắm đâu. Vì đơn giản 
    mọi người thường nhớ về ngày 20/11 hơn. Nhưng sau càng ngày lớn hơn anh lại càng thấy thích ngày sinh của mình. Đơn giản vì ngày 19/11 được chọn làm ngày Quốc tế Đàn ông(Úi dùi ui tuyệt vời).
    À quên ngày này thuộc cung Bọ Cạp. 
    <img src="images/hehe.jpg" alt="alternatetext">
    - Trôi theo điều thứ 3: Có một lần em hỏi anh về bố mẹ anh. Lần đấy anh lo lắng thật sự, lần đấy anh vòng vo không trả lời em hẳn. Đơn giản không phải anh sợ người khác biết hay như nào đâu. Mà anh ghét phải nhớ lại khoảng thời gian đấy.
    Bố mẹ anh chia tay khá sớm. Trong khoảng thời gian đấy anh hay được hỏi câu hỏi nhất là: Cháu yêu ai hơn? Hoặc đơn giản hơn là: Bố mẹ mày chia tay rồi à? Khoảng thời gian đấy anh còn nhỏ nên hồn nhiên lắm.
    Không hay nghĩ như bây giờ nên ai hỏi cũng cười cợt như thể chẳng có chuyện gì xảy ra cả. Giờ lớn hơn một chút, ít nói hơn nhưng lại cảm nhận nhiều hơn. 
    - Điều thú nhận thứ 4: Mọi người hay bảo là anh người thích ru rú ở nhà nhưng trên thực tế là không phải. Anh thích đi đây đi đó, gặp người này người kia, sống cuộc sống của họ trong khoảng thời gian ngắn.
    Lúc stressed, anh thường sẽ nghỉ vài ngày đến vùng đất lạ, không chăm chăm vào màn hình điện thoại, máy tính nữa mà sẽ lang thang đi khắm nơi. Đơn cử như năm 4 đại học, anh bị stressed nặng khi làm đồ án tốt nghiệp.
    Lần đấy anh sợ rằng làm đồ án fail sẽ làm mất mặt thầy nên đã trốn vào Sài Gòn một tuần để lấy lại mục tiêu của bản thân mình, tại sao bắt đầu, tiếp diễn ra sao.. Sau mỗi lần như thế con người ta lại làm mới lại bản thân 
    để băng qua phía trước.
    <iframe width="580" height="350" src="https://www.youtube.com/embed/5i8bezxh-eQ" frameborder="0" allowfullscreen></iframe>
    - Fact 5: Anh luôn ước mình sẽ có một tiệm sách cũ. Ước mơ này có từ nhỏ luôn. Hồi xưa ông bà anh có một tiệm sách nhỏ hay bán lại sách cũ cho trẻ em ở trên khu anh ở. Chắc từ đây anh có sở thích ước mơ này. Mùi sách cũ có
    một cái gì đấy khó diễn tả cực. Đến thời nay, chắc ít có người nào mua sách cũ nữa. Giờ chỉ cần ngồi nhà lướt điện thoại trên Tiki rồi đặt mua là đã có ngay bao nhiêu là sách rồi. Chẳng còn ai lê la tiệm sách cũ để tìm mua như 
    trước nữa. 

    Trên là 5 điều anh ghi trên web trước, còn 5 điều còn lại nếu em muốn nghe anh sẽ viết tiếp. =)).



# Projects Section
projects_title: Anh thích em!

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
